### ISSUE TITLE
Error: Failed to install provider v2.2.0

### ISSUE THREAD

**Issue by brandocorp** [hashicorp/terraform-provider-local#111] opened 2022-03-10 21:18 UTC
### Terraform CLI and Provider Versions

Terraform CLI: 1.0.11
Provider: hashicorp/local v2.2.0

### Terraform Configuration

```terraform
n/a
```

### Expected Behavior

When running `terraform init` it downloads the provider.

### Actual Behavior

When running `terraform init` it throws an error message.

```
╷
│ Error: Failed to install provider
│ 
│ Error while installing hashicorp/local v2.2.0: archive has incorrect checksum zh:507776b1e1901fdd6450a88298fc87a27a508e0c01405c7e8e8f2037d5963afe (expected
│ zh:f427480d3ec953434eccf21544b0b2be63595634e4e79a53575ceb892f22230d)
╵
```

### Steps to Reproduce

1. `terraform init`

### How much impact is this issue causing?

Medium

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by a053a** [comment] 2022-03-10 21:20
We're seeing this issue too.

- Downloading plugin for provider "local" (hashicorp/local) 2.2.0...
[31m
[0m[1m[31mError installing provider "local": Checksums did not match for /tmp/getter561146354/archive.
Expected: f427480d3ec953434eccf21544b0b2be63595634e4e79a53575ceb892f22230d
Got: 507776b1e1901fdd6450a88298fc87a27a508e0c01405c7e8e8f2037d5963afe
*sha256.digest.[0m[31m

**Comment by skjensen** [comment] 2022-03-10 21:21
Quickfix is locking it to v2.1.0 

    local = {
      source = "hashicorp/local"
      version = "= 2.1.0"
    }

**Comment by alexlokshin-czi** [comment] 2022-03-10 21:22
Same issue here. 
```
Error while installing hashicorp/local v2.2.0: archive has incorrect SHA-256
checksum 507776b1e1901fdd6450a88298fc87a27a508e0c01405c7e8e8f2037d5963afe
(expected f427480d3ec953434eccf21544b0b2be63595634e4e79a53575ceb892f22230d)
```

**Comment by comjf** [comment] 2022-03-10 21:29
Well this shows me I need to use lockfiles! If only the m1 mac issues requiring manually patched providers didn't make things complicated using both arm/x86 deployment architectures!

**Comment by f0rkz** [comment] 2022-03-10 21:38
Confirmed as well...

**Comment by spliskamatyshak** [comment] 2022-03-10 21:41
No quick fix if using terraform-aws-lambda module from the registry.

**Comment by f0rkz** [comment] 2022-03-10 21:44
Its obnoxious these changes just slip in and we have to scramble to fix them...

**Comment by spliskamatyshak** [comment] 2022-03-10 21:49
This needs to be escalated. All of our deployments that use registry modules with local included are failing.

**Comment by spliskamatyshak** [comment] 2022-03-10 22:02
> Quickfix is locking it to v2.1.0
> 
> ```
> local = {
>   source = "hashicorp/local"
>   version = "= 2.1.0"
> }
> ```

found a place to put this that forces this older verion

**Comment by bruceadams** [comment] 2022-03-10 22:04
@spliskamatyshak please share where! My attempts so far have not been effective.

**Comment by spliskamatyshak** [comment] 2022-03-10 22:09
> @spliskamatyshak please share where! My attempts so far have not been effective.

I had a versions.tf with another provider defined. I added it in our module that ultimately calls the registry module. If you don't have versions specified, you should be able to just add it.

`terraform {
  required_version = ">= 1.0"
  required_providers {
    local = {
      source = "hashicorp/local"
      version = "2.1.0"
    }
  }
}`

**Comment by Layer8Err** [comment] 2022-03-10 22:14
It looks like this fails when locking for linux_amd64:

`terraform providers lock -platform=darwin_amd64 -platform=linux_amd64 -platform=windows_amd64`

Locks for darwin_amd64 and windows_amd64 don't throw any errors:

`terraform providers lock -platform=darwin_amd64 -platform=windows_amd64`

**Comment by brandocorp** [comment] 2022-03-10 22:14
> @spliskamatyshak please share where! My attempts so far have not been effective.

```hcl
terraform {
    required_providers {
        local = {
            source = "hashicorp/local"
            version = "= 2.1.0"
        }
    }
}
```

**Comment by tsybanov** [comment] 2022-03-10 22:15
Checksum has been updated https://github.com/hashicorp/terraform-provider-local/commit/4ec9a9a32e746f17fe834425ca3175213128bfb9

**Comment by earchibald-lv** [comment] 2022-03-10 22:20
It is still failing for me with a job launched after the "Checksum has been updated" comment.

**Comment by earchibald-lv** [comment] 2022-03-10 22:22
> It is still failing for me with a job launched after the "Checksum has been updated" comment.

Could be CDN convergence -- I will give it a bit and try again.

**Comment by tsybanov** [comment] 2022-03-10 22:22
> It is still failing for me with a job launched after the "Checksum has been updated" comment.

I think it hasn't been published yet due to CDN distributions https://registry.terraform.io/providers/hashicorp/local/latest

**Comment by spliskamatyshak** [comment] 2022-03-10 22:27
> Checksum has been updated [4ec9a9a](https://github.com/hashicorp/terraform-provider-local/commit/4ec9a9a32e746f17fe834425ca3175213128bfb9)

How long before latest shows as 2.2.1 in the registry?

**Comment by tsybanov** [comment] 2022-03-10 22:27
https://registry.terraform.io/providers/hashicorp/local/latest

`2.2.1` is live

**Comment by tsybanov** [comment] 2022-03-10 22:29
I can confirm that the issue is resolved, and it could be closed

**Comment by bflad** [comment] 2022-03-10 22:32
Hi folks 👋  Thank you for reporting this and apologies for the unexpected 2.2.0 release issue. A new 2.2.1 release has been published to releases.hashicorp.com and the public Terraform Registry. Can you confirm that the new release is working as expected?

**Comment by mpope9** [comment] 2022-03-10 22:34
@bflad Works for me now.

**Comment by brandocorp** [comment] 2022-03-10 22:37
@bflad it is working for me now. Thanks to all for sorting it out!

**Comment by kris-Nabis** [comment] 2022-03-10 22:39
It is now working for me as well. Thanks!

**Comment by skjensen** [comment] 2022-03-10 22:40
Confirmed, working with v2.2.1

**Comment by dnorton31** [comment] 2022-03-10 22:41
Thank you, this helped me realize a CI script was not properly using the lockfile.

**Comment by detro** [comment] 2022-03-11 10:03
Apologies folks, there was an issue with our release automation when I prepared `2.2.0`, this caused binary and checksums being built against 2 different consecutive commits. 

Closing.

**Closed by detro** 2022-03-11 10:03 UTC
Labels: bug
