### ISSUE TITLE
local_file resource 

### ISSUE THREAD

**Issue by cloud-operations** [hashicorp/terraform-provider-local#122] opened 2022-04-22 18:17 UTC
### Terraform CLI and Provider Versions

Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/hashicorp/local v2.2.2

### Terraform Configuration

```terraform
resource "local_file" "yes" {
  filename = "hello.txt"
}
```

### Expected Behavior

file hello.txt should be created

### Actual Behavior

Error: Invalid combination of arguments
│ 
│   with local_file.yes,
│   on local.tf line 1, in resource "local_file" "yes":
│    1: resource "local_file" "yes" {

one of `content,content_base64,sensitive_content,source` must be specified

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### How much impact is this issue causing?

Low

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stdtom** [comment] 2022-04-30 12:31
duplicate of #116

**Closed** 2022-05-18 12:09 UTC
Labels: bug
